name: Daily PR Report

on:
  schedule:
    - cron: '0 8 * * *'   # Runs daily at 08:00 UTC
  workflow_dispatch:      # Manual trigger 

jobs:
  send_pr_report:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      TEAM_EMAILS: ${{ secrets.TEAM_EMAILS }}
      GITHUB_REPOS: ${{ secrets.GITHUB_REPOS }}
      SMTP_SERVER: smtp.gmail.com
      SMTP_PORT: 587

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run PR report script
        run: python scripts/send_pr_report.py
